name: soundsetr
description: Change Outlook on Mac notification sounds
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  macos_ui: ^2.0.0
  path_provider: ^2.1.1
  macos_window_utils: ^1.4.0
  watcher: ^1.1.0
  system_theme: ^2.3.1
  flutter_staggered_grid_view: ^0.7.0
  window_manager: ^0.3.7
  flutter_archive: ^5.0.0
  plist_parser: ^0.0.11
  sanitize_filename: ^1.0.5
  path: ^1.8.3
  url_launcher: ^6.2.1
  audioplayers: ^5.2.1
  io: ^1.0.4
  flutter_shake_animated: ^0.0.5
  file_picker: ^6.1.1
  ffmpeg_kit_flutter: ^6.0.3
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  streaming_shared_preferences: ^2.0.0
  flutter_markdown: ^0.6.18+2
  desktop_drop: ^0.4.4
  cross_file: ^0.3.3+7
  macos_file_picker: ^0.3.0
  accessing_security_scoped_resource: ^2.0.0
  propertylistserialization: ^1.3.0
  app_links: ^3.4.5
  protocol_handler: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  dependency_validator: ^3.2.3
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/

flutter_launcher_icons:
  image_path: "res/appicon.png"
  macos:
    generate: true
    image_path: "res/appicon.png"